apiVersion: v1
kind: Service
metadata:
 name: influxdb
 labels:
  app: services
  svc: influxdb
spec:
 type: ClusterIP 
 selector:
  app: services
  svc: influxdb
 ports:
  - name: influxdb-port
    protocol: TCP
    port: 8086
