apiVersion: v1
kind: Service
metadata:
 name: grafana
 labels:
  app: services
  svc: grafana
spec:
 externalIPs:
  - 192.168.49.24
 type: LoadBalancer
 selector:
  app: services
  svc: grafana
 ports:
  - name: grafana-port
    protocol: TCP
    port: 3000 
