apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  app: services
  svc: nginx
spec:
 selector:
  matchLabels:
   app: services
   svc: nginx
 template:
  metadata:
   labels:
    app: services
    svc: nginx
  spec:
   containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Never
      ports:
       - name: http
         containerPort: 80
         protocol: TCP
       - name: https
         containerPort: 443
         protocol: TCP
      volumeMounts:
       - name: nginx-conf-nginx
         mountPath: /etc/nginx/nginx.conf
         subPath: nginx.conf
       - name: nginx-index
         mountPath: /home/www/index.html
         subPath: index.html
   volumes:
    - name: nginx-conf-nginx
      configMap:
       name: nginx-conf-nginx
    - name: nginx-index
      configMap:
       name: nginx-index
