apiVersion: v1
kind: Service
metadata:
 name: nginx
 labels:
  app: services
  svc: nginx
spec:
 externalIPs:
  - 192.168.49.24
 selector:
  app: services
  svc: nginx
 ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
 type: LoadBalancer
