apiVersion: v1
kind: Service
metadata:
 name: nginx
 annotations:
  metallb.universe.tf/allow-shared-ip: kub-ip 
 labels:
  app: services
  svc: nginx
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: nginx
 ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
