apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
 - name: pma-conf
   files:
    - srcs/config.inc.php
 - name: nginx-conf-pma
   files:
    - srcs/nginx.conf

resources:
 - volume.yaml
 - service.yaml
 - deployment.yaml
