apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin
 labels:
  app: services
  svc: phpmyadmin
spec:
 externalIPs:
  - 192.168.49.24
 type: LoadBalancer
 selector:
  app: services
  svc: phpmyadmin
 ports:
  - name: pma-port
    protocol: TCP
    port: 5000
