apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin
 annotations:
  metallb.universe.tf/allow-shared-ip: kub-ip 
 labels:
  app: services
  svc: phpmyadmin
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: phpmyadmin
 ports:
  - name: pma-port
    protocol: TCP
    port: 5000
