apiVersion: v1
kind: PersistentVolume
metadata:
 name: pma-volume
 labels:
  svc: phpmyadmin
  app: services
spec:
 storageClassName: phpmyadmin
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 hostPath:
  path: "/mnt/phpmyadmin"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pma-claim
 labels:
  svc: phpmyadmin
  app: services
spec:
 storageClassName: phpmyadmin
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 1Gi
