apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps-deployment
 labels:
  app: services
  svc: ftps 
spec:
 selector:
  matchLabels:
   app: services
   svc: ftps
 template:
  metadata:
   labels:
    app: services
    svc: ftps
  spec:
   containers:
    - name: ftps
      image: ftps
      imagePullPolicy: Never
      ports:
       - name: ftps-port
         containerPort: 21
         protocol: TCP
