apiVersion: v1
kind: Service
metadata:
 name: ftps
 labels:
  app: services
  svc: ftps
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: ftps
 ports:
  - name: wp-port
    protocol: TCP
    port: 21
    nodePort: 30021
