apiVersion: v1
kind: Service
metadata:
 name: phmyadmin
 labels:
  app: services
  svc: phpmyadmin
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: phpmyadmin
 ports:
  - name: pma-port
    protocol: TCP
    port: 5000
    nodePort: 30500
