apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  app: services
  svc: nginx
spec:
 selector:
  matchLabels:
   app: services
   svc: nginx
 template:
  metadata:
   labels:
    app: services
    svc: nginx
  spec:
   containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Never
      ports:
       - name: http
         containerPort: 80
         protocol: TCP
       - name: https
         containerPort: 443
         protocol: TCP