apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    run : nginx
    app: services
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
      app: services
  template:
    metadata:
      labels:
        run: nginx
        app: services
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: config-map-nginx