apiVersion: v1
kind: Service
metadata:
 name: nginx
 labels:
  app: services
  svc: nginx
spec:
 selector:
  app: services
  svc: nginx
 ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30443
 type: LoadBalancer