apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress-deployment
 labels:
  app: services
  svc: wordpress
spec:
 selector:
  matchLabels:
   app: services
   svc: wordpress
 template:
  metadata:
   labels:
    app: services
    svc: wordpress
  spec:
   containers:
    - name: wordpress
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      image: wordpress
      imagePullPolicy: Never
      ports:
       - name: wp-port
         containerPort: 5050
         protocol: TCP
  #     volumeMounts:
  #      - name: wordpress-persistent-storage
  #        mountPath: /home/www/db
  #  volumes:
  #   - name: wordpress-persistent-storage
  #     persistentVolumeClaim:
  #      claimName: wp-pv-claim