apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
 - name: nginx-conf-wp
   files:
    - srcs/nginx.conf


resources:
 - volume.yaml
 - service.yaml
 - deployment.yaml
