apiVersion: v1
kind: Service
metadata:
 name: wordpress
 labels:
  app: services
  svc: wordpress
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: wordpress
 ports:
  - name: wp-port
    protocol: TCP
    port: 5050
    nodePort: 30050