apiVersion: v1
kind: Service
metadata:
 name: wordpress
 labels:
  app: services
  svc: wordpress
spec:
 externalIPs:
  - 192.168.49.24
 type: LoadBalancer
 selector:
  app: services
  svc: wordpress
 ports:
  - name: wp-port
    protocol: TCP
    port: 5050
