apiVersion: v1
kind: Service
metadata:
 name: wordpress
 annotations:
  metallb.universe.tf/allow-shared-ip: kub-ip 
 labels:
  app: services
  svc: wordpress
spec:
 type: LoadBalancer
 selector:
  app: services
  svc: wordpress
 ports:
  - name: wp-port
    protocol: TCP
    port: 5050
