apiVersion: v1
kind: Service
metadata:
 name: mysql
 labels:
  app: services
  svc: mysql
spec:
 selector:
  app: services
  svc: mysql
 ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
 type: ClusterIP