apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    svc: mysql
spec:
  storageClassName: mysql
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    svc: mysql
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi