apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps
 labels:
  app: services
  svc: ftps 
spec:
 selector:
  matchLabels:
   app: services
   svc: ftps
 template:
  metadata:
   labels:
    app: services
    svc: ftps
  spec:
   containers:
    - name: ftps
      image: ftps
      imagePullPolicy: Never
      env:
       - name: KUB_IP
         valueFrom:
          secretKeyRef:
           name: kub-ip
           key: kub-ip
      ports:
       - containerPort: 20
       - containerPort: 21
       - containerPort: 30100
       - containerPort: 30101
       - containerPort: 30102
       - containerPort: 30103
       - containerPort: 30104
