apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps-deployment
 labels:
  app: services
  svc: ftps 
spec:
 selector:
  matchLabels:
   app: services
   svc: ftps
 template:
  metadata:
   labels:
    app: services
    svc: ftps
  spec:
   containers:
    - name: ftps
      image: ftps
      imagePullPolicy: Never
      ports:
       - name: ftps-port0
         containerPort: 20
         protocol: TCP
       - name: ftps-port1
         containerPort: 21
         protocol: TCP
       - name: ftps-port2
         containerPort: 30100
         protocol: TCP
       - name: ftps-port3
         containerPort: 30101
         protocol: TCP
       - name: ftps-port4
         containerPort: 30102
         protocol: TCP
       - name: ftps-port5
         containerPort: 30103
         protocol: TCP
