apiVersion: v1
kind: Service
metadata:
 name: ftps
 labels:
  app: services
  svc: ftps
spec:
 type: LoadBalancer
 externalIPs:
  - 192.168.49.24
 selector:
  app: services
  svc: ftps
 ports:
  - name: ftps-port0
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps-port1
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-port2
    protocol: TCP
    port: 30100
  - name: ftps-port3
    protocol: TCP
    port: 30101
  - name: ftps-port4
    protocol: TCP
    port: 30102
  - name: ftps-port5
    protocol: TCP
    port: 30103
